op-rs/op-reth

crates/primitives/src/transaction/mod.rs
crates/primitives/src/transaction/optimism.rs

Small changes to the deposit transaction primitive:
* Deposit transactions don't have nonces; This value always defaults to `0`.
* Add getters for `source_hash`, `mint`, & `is_system_transaction` that may be enabled by the `optimism` feature flag.
* Temporarily panic when encoding a deposit transaction with a non-zero signature. We should handle this higher up, panicking here isn't the right move.

Small changes to the deposit tx primitive

---

crates/interfaces/Cargo.toml
crates/primitives/src/transaction/mod.rs
crates/primitives/src/transaction/optimism.rs

build was failing when I added "optimism" to the default reth features.
after the rebasing I noticed the second issue with Deposit tx match missing in one file.

fix build failures with optimism feature

---

crates/primitives/src/chain/spec.rs

Populate genesis hash appropriately, add pre and post conditions for the regolith fork

Fix optimism_goerli_forkids test with genesis and regolith conditions

---

crates/primitives/src/transaction/mod.rs
crates/primitives/src/transaction/tx_type.rs

Proposed as an alternative to #16, adding the variable-length encoding directly in the `to_compact` and `from_compact` implementations for `TxType` and `Transaction`.
For the purposes of backwards-compatibility, this continues to reserve 2 bits to encode the transaction type data in the serialized entity's `StructFlags`. Whenever the value is greater than or equal to 3, we use 3 as the 2-bit identifier and encode the full type value to the buffer as a single byte.
This has the somewhat-counterintuitive behavior of conditionally splitting the data across the (repurposed) "length" value as well as the buffer, while the type easily fits within the `usize` return value on all architectures.
Note that with this change, a compact-serialized Transaction will have a 1 or 2-byte metadata header …

Add variable-length compact support for TxType and Transaction

---

crates/primitives/src/chain/spec.rs

Add missing `optimism` config to the `DEV` chainspec

[trivial] Fix dev chainspec when optimism feature enabled

---

bin/reth/src/args/mod.rs
bin/reth/src/args/rollup_args.rs
bin/reth/src/node/mod.rs

Adds --rollup.sequencerhttp and --rollup.disabletxpoolgossip flags to op-reth node (without implementations) per issue https://github.com/paradigmxyz/reth/issues/3794

add op-node specific command line flags

---

crates/net/eth-wire/Cargo.toml
crates/primitives/src/receipt.rs

* Encode/decode optional `Receipt.deposit_nonce` field for `Deposit` transaction receipts
* Increases the length of the RLP list by 1 element when a deposit nonce is present.
* Ensure that the appropriate RLP length is written for all non-legacy transaction receipts, including Deposits
* Add custom implementation of `arbitrary` and `arbitrary_with` for the `Receipt` type, ensuring that `Receipt.deposit_nonce` is only `Some` whenever the transaction type is `TxType::DEPOSIT`
Open questions:
* Is there a simpler way to define this arbitrary/arbitrary_with strategy leveraging the existing `main_codec` macro?
Fixes the following tests:
```
reth-eth-wire types::receipts::ReceiptsTests::proptest
```

op-reth: Fix serialization/deserialization for Deposit Receipts

---

bin/reth/src/args/rollup_args.rs

This PR adds a `rollup.compute-pending-block` flag to the node cli as a rollup arg.
By default, the pending block is computed using the latest block to preserve tx pool privacy.
This flag allows the node operator to compute the pending block using the tx pool.
**Testing**
No testing required to keep the diff minimal and consistent with op-geth.
**Metadata**
Addresses part of #4004.

feat(node): Add Compute Pending Block Rollup CLI Option

---

bin/reth/src/args/rpc_server_args.rs
crates/consensus/auto-seal/src/lib.rs
crates/consensus/auto-seal/src/task.rs
crates/consensus/common/src/validation.rs
crates/payload/builder/src/payload.rs
crates/primitives/src/basefee.rs
crates/primitives/src/chain/spec.rs
crates/primitives/src/constants/mod.rs
crates/primitives/src/header.rs
crates/rpc/rpc-builder/src/auth.rs
crates/rpc/rpc/src/eth/api/block.rs
crates/rpc/rpc/src/eth/api/call.rs
crates/rpc/rpc/src/eth/api/fees.rs
crates/rpc/rpc/src/eth/api/mod.rs
crates/rpc/rpc/src/eth/api/server.rs
crates/rpc/rpc/src/eth/api/state.rs
crates/rpc/rpc/src/eth/api/transactions.rs
crates/storage/provider/src/test_utils/mock.rs
crates/transaction-pool/src/lib.rs
crates/transaction-pool/src/maintain.rs

1559 base fee computation is parameterized by elasticity_muliplier and base_fee_change_denominator. Currently these values are obtained through (conditionally compiled) constants, which does not allow for them to be configured via chain config as required by optimism superchains.
This change makes all base fee computations obtain the parameter values via the ChainSpec.
addresses https://github.com/paradigmxyz/reth/issues/3750

use the parameters from the optimism config in 1559 base fee computation

---

crates/primitives/src/transaction/signature.rs

Updates signature tests in `reth-primitives` to be compatible with the special-case optimism serialization for zero signatures (`R: 0, S: 0, V: 0`).
Adds optimism-only test cases for this zero signature behavior
Fixes the following tests:
```
reth-primitives transaction::signature::tests::test_encode_and_decode_with_eip155_chain_id
reth-primitives transaction::signature::tests::test_payload_len_with_eip155_chain_id
reth-primitives transaction::signature::tests::test_v
```

op-reth: Fix reth-primitives signature tests

---

bin/reth/src/args/rpc_server_args.rs
crates/consensus/auto-seal/src/lib.rs
crates/consensus/auto-seal/src/task.rs
crates/consensus/common/src/validation.rs
crates/payload/builder/src/payload.rs
crates/primitives/src/basefee.rs
crates/primitives/src/chain/spec.rs
crates/primitives/src/constants/mod.rs
crates/primitives/src/header.rs
crates/rpc/rpc-builder/src/auth.rs
crates/rpc/rpc/src/eth/api/block.rs
crates/rpc/rpc/src/eth/api/call.rs
crates/rpc/rpc/src/eth/api/fees.rs
crates/rpc/rpc/src/eth/api/mod.rs
crates/rpc/rpc/src/eth/api/server.rs
crates/rpc/rpc/src/eth/api/state.rs
crates/rpc/rpc/src/eth/api/transactions.rs
crates/storage/provider/src/test_utils/mock.rs
crates/transaction-pool/src/lib.rs
crates/transaction-pool/src/maintain.rs

Reverts anton-rs/op-reth#32 since we are [fixing upstream](https://github.com/paradigmxyz/reth/pull/3992) in a way that will make this have ugly conflicts. Will redo this change after the upstream PR is merged.

Revert "use the parameters from the optimism config in 1559 base fee computation"

---

crates/revm/src/executor.rs
crates/revm/src/optimism.rs

* Only fetch L1 block info and compute l1 cost when the chain spec includes an Optimism config
* Only transfer L1 Cost and Base Fee to the respective vaults when the chain spec includes an Optimism config
Addresses the following tests (#31):
```
reth-revm executor::tests::sanity_execution
reth-revm executor::tests::test_selfdestruct
```
Follow-up: Add new test cases which cover the cases where the chain has Optimism enabled

Ensure that block execution maintains L1 compatibility with optimism feature enabled

---

crates/primitives/src/basefee.rs

Very small PR to add an optimism feature flag specific test for the next base fee calculation in `calculate_next_block_base_fee`.

feat(primitives): Add Optimism next base fee test

---

crates/primitives/src/chain/spec.rs

Updates the Optimism goerli chain spec to add the bedrock hard fork.
This is a block-based fork condition and is based on the optimism goerli rollup config in the [optimism monorepo](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/chaincfg/chains.go#L51). Since the committed code in trunk is bedrock, we take this L2 genesis block number as the bedrock transition block.

fix(primitives): Update Optimism Goerli Chain Spec with Bedrock Hardfork

---

crates/primitives/src/chain/spec.rs

Updates the `regolith_activated` function of the `ChainBuilder` to accept a `u64` timestamp parameter.

fix(primitives): Update ChainBuilder Regolith with Timestamp Parameter

---

crates/primitives/src/transaction/mod.rs
crates/primitives/src/transaction/optimism.rs
crates/revm/src/executor.rs

Adds an optional nonce field to `TxDeposit`, which was added in the Regolith hardfork. Must be `None` prior to the Regolith hardfork.
Will be used to hydrate the receipts in the `User API Enhancements` section of the `op-geth` diff. https://github.com/ethereum-optimism/op-geth/blob/8f8af46ec728a79137d449891fc1827e1763cd7e/core/types/receipt.go

fix(primitives): Add optional nonce to `DepositTx` for Regolith

---

crates/consensus/common/src/validation.rs
crates/primitives/src/chain/spec.rs

Fixes up some todo comments in the code:
1. Change base fee validation to be altered for optimism by the chainspec configuration over the feature flag. This is part of ensuring that the reth binary compiled with the optimism feature flag can still run as an L1 client.
2. Remove fork timestamp TODOs (already correct, shanghai and cancun should not be scheduled yet on OP chains)
3. Remove TODO comment above `optimism` flag in the `ChainSpec` - already removed the `OptimismConfig` in favor of the `bool` and `BaseFeeParams`.

chore: Fix up some TODOs

---

bin/reth/src/cli/ext.rs
bin/reth/src/node/mod.rs
crates/consensus/beacon/src/engine/mod.rs
crates/net/network/src/config.rs
crates/payload/basic/src/lib.rs
crates/payload/basic/src/optimism.rs
crates/payload/builder/src/error.rs
crates/payload/builder/src/payload.rs
crates/payload/builder/src/service.rs
crates/revm/src/executor.rs
crates/rpc/rpc-engine-api/src/engine_api.rs

Adds the changes to the engine API and block building logic defined in the [execution engine specifications](https://github.com/ethereum-optimism/optimism/blob/develop/specs/exec-engine.md#engine-api) in the optimism monorepo.

feat: Engine API + Block Building modifications

---

bin/reth/Cargo.toml
bin/reth/src/node/mod.rs

This adds a default `ethereum` feature flag to the bin crate and an associated [compile error](https://doc.rust-lang.org/std/macro.compile_error.html) to prevent compilation if **neither** `ethereum` nor `optimism` are specified as feature flags.
This is in reference to discussion [here](https://github.com/anton-rs/op-reth/pull/59/files#r1293454888)
Notice, we cannot perform a mutually exclusive feature flag check since any runs with `--all-features` will cause compilation to break.

feat: Inclusive Default Feature Flags

---

crates/payload/basic/src/lib.rs
crates/payload/basic/src/optimism.rs
crates/primitives/src/receipt.rs
crates/rpc/rpc-types-compat/src/transaction/mod.rs
crates/rpc/rpc-types/src/eth/transaction/mod.rs
crates/rpc/rpc-types/src/eth/transaction/receipt.rs
crates/rpc/rpc/src/eth/api/transactions.rs

Adds OP fields to `rpc-types`' `Receipt` and `Transaction`

feat: Add Optimism fields to `rpc-types`

---

Cargo.lock
crates/consensus/common/src/validation.rs
crates/revm/Cargo.toml
crates/revm/src/executor.rs
crates/revm/src/optimism.rs
crates/transaction-pool/Cargo.toml
crates/transaction-pool/src/lib.rs
crates/transaction-pool/src/noop.rs
crates/transaction-pool/src/test_utils/mock.rs
crates/transaction-pool/src/traits.rs
crates/transaction-pool/src/validate/eth.rs

Contains all Changes for the Tx Pool Cost Updates.
Closes https://github.com/paradigmxyz/reth/issues/3751
<details>
<summary>Follows op-geth's `validateTxBasics` function logic, screenshot in toggle.</summary>
</details>
<details>
<summary>Applies the l1 cost function to tx pool validation.</summary>
</details>
❌ Transaction Journaling - this should not be needed
<details>
<summary>Adds transaction journaling.</summary>
</details>

feat(transaction-pool): Tx Pool Cost Updates

---

crates/payload/basic/src/optimism.rs
crates/revm/src/executor.rs

Fixes the optimism execution logic to be backwards compatible with L1 when compiled with all feature flags.

chore: Fix tests with all feature flags enabled

---

crates/revm/src/optimism/executor.rs

Fixes a bug where the evm's `CfgEnv` did not have its configuration reset after a deposit fails with an EVM failure. This caused a diff in the gas consumption around block 3.27M ([this tx](https://goerli.basescan.org/tx/0x25820f992f05cb0f7b510df078867f37c527dc4a0bb365ce56b3196f71d8ec2c)) on base goerli due to an `SSTORE` not receiving a gas refund.

fix(executor): Deposit Failure `CfgEnv` reset

---

crates/payload/basic/src/optimism.rs
crates/revm/src/optimism/executor.rs

Fixes a mishap in gas reporting for reverting deposits post-Regolth.

fix: Gas accounting for reverting deposits post-regolith

---

crates/payload/basic/src/optimism.rs
crates/revm/src/optimism/executor.rs

Patches a condition where a haulted tx doesn't report all gas limit used.

fix: Haulted deposit regolith gas

---

crates/primitives/src/proofs.rs
crates/primitives/src/transaction/tx_type.rs
crates/revm/src/executor.rs
crates/rpc/rpc/src/eth/api/block.rs

Fixes and adds a few comments. Should be enough for upstream pointing.

fix: comments

---

Cargo.lock
Cargo.toml

Removes the patch of the `c-kzg` library, was left over in a conflict.

Remove `c-kzg` patch from diff

---

crates/primitives/src/chain/spec.rs
crates/primitives/src/constants/mod.rs

..also removed the OP_*_DEFAULT constants which were just adding clutter.

fix the base fee params for base mainnet

---

crates/payload/basic/src/optimism.rs
crates/revm/Cargo.toml
crates/revm/src/optimism/executor.rs
crates/revm/src/optimism/mod.rs

Pre-parse the address constants used in hot functions during the execution & block building.
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1307179990.

perf(executor): pre-parse address constants

---

bin/reth/src/lib.rs

Documents the additional feature flags added to the reth binary as requested in https://github.com/paradigmxyz/reth/pull/4377#discussion_r1307161456.

fix: Document Additional Feature Flags

---

bin/reth/src/cli/mod.rs
bin/reth/src/node/mod.rs

Moves the compile error to the reth cli runner entrypoint as opposed to `node` subcommand specific entrypoint.

fix: Feature Flag Compiling Errors

---

crates/primitives/src/transaction/mod.rs

Adds a comment as to why an identifier of `3` means we must read a full byte from the buffer in order to match on transaction types that are larger than two bits fitting inside the identifier.

fix: Comment on the Compat Tx Type Buffer Reading 

---

crates/primitives/src/transaction/mod.rs

Fixes the nit in https://github.com/paradigmxyz/reth/pull/4377#discussion_r1307177879 to use the `TransactionSigned::from_transaction_and_signature` associated helper function to instantiate the signed transaction.

fix: Signed Transaction Instantiation

---

crates/rpc/rpc-types/src/eth/transaction/receipt.rs

Fixes the suggestion in https://github.com/paradigmxyz/reth/pull/4377#discussion_r1307180917 to remove the optimism feature field serde renames here since they are redundant and handled by the top-level serde camel case rename.

fix: Redundant Serde Camel Case Renames in RPC Transaction Receipt

---

bin/reth/src/args/utils.rs

Uses [kebab-case](https://en.wiktionary.org/wiki/kebab_case) for chain names instead of snake case.
Also adds `base-goerli` and `base` chain spec parsing tests to the args utils.

fix: Switch chain names to kebab casing

---

crates/primitives/src/serde_helper/mod.rs

Addresses upstream review comment @ https://github.com/paradigmxyz/reth/pull/4377#discussion_r1307174072 to remove the optimism feature flag above the U64 serde helper.

fix: Remove Optimism Feat on U64 Serde Helper

---

crates/primitives/src/chain/mod.rs

Updates base mainnet to use named ethers chain over hardcoded chain id.

fix: Base Mainnet Chain Accessor

---

crates/payload/basic/src/optimism.rs
crates/payload/builder/src/error.rs

Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376096763

fix(payload): Grouped Optimism Error

---

crates/rpc/rpc/src/eth/api/transactions.rs
crates/rpc/rpc/src/eth/error.rs

- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376124239
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376125915

fix(rpc): forward to sequencer function, rpc error type

---

bin/reth/src/args/payload_builder_args.rs
bin/reth/src/node/mod.rs

Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376058344

fix(bin): Fix Compute Pending Block Docs

---

crates/primitives/src/revm/env.rs
crates/primitives/src/transaction/tx_value.rs
crates/revm/src/optimism/processor.rs
crates/transaction-pool/src/validate/eth.rs

- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376116551
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376115084

fix(primitives): pub U256, import spacing

---

crates/net/network/src/config.rs
crates/net/network/src/manager.rs
crates/net/network/src/network.rs
crates/net/network/src/transactions.rs

Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376089632

fix: Optimism Network

---

crates/revm/src/optimism/mod.rs
crates/rpc/rpc/src/eth/api/block.rs
crates/rpc/rpc/src/eth/api/mod.rs
crates/rpc/rpc/src/eth/api/optimism.rs
crates/rpc/rpc/src/eth/api/transactions.rs
crates/transaction-pool/src/validate/eth.rs

Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379869691
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379875131
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379883585
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379885712
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379886996
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1379890674

fix: addresses review comments

---

bin/reth/src/cli/mod.rs
crates/rpc/rpc/src/eth/api/transactions.rs

Fork of #157 that removes the runtime check for the `optimism` feature flag. Going to take the plunge and just split the bins out instead.

@merklefruit nits

---

crates/rpc/rpc/src/eth/api/mod.rs
crates/rpc/rpc/src/eth/api/transactions.rs

Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382502041

fix(rpc): Move reqwest client into EthApiInner

---

bin/reth/src/node/mod.rs
crates/primitives/src/chain/spec.rs
crates/primitives/src/constants/mod.rs
crates/primitives/src/transaction/mod.rs
crates/rpc/rpc-types-compat/src/transaction/mod.rs

Nits addressed:
- https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382503344
- https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382503674
- https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382503733
- https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382504437
- https://github.com/paradigmxyz/reth/pull/4377#discussion_r1382504475

chore: PR comments & nits

---

.github/CODEOWNERS

@dhyaniarun1993 @itschaindev @sadiq1971 @meyer9 think these are the only crates we will need to touch. can update as we go. ideally the new logic will only live inside of _crates/optimism_, but we may need to generalise some components in the other crates I listed and make them customisable up at SDK (node builder _crates/node_) level to achieve this.

chore(codeowners): Set codeowners for historical proofs work stream

---

Cargo.lock
Cargo.toml
crates/exex/external-proofs/Cargo.toml
crates/exex/external-proofs/src/lib.rs

feat: create initial external-proofs ExEx crate
