op-rs/op-reth

- crates/primitives/src/chain/spec.rs
- crates/primitives/src/hardfork.rs
- crates/primitives/src/transaction/mod.rs
- crates/primitives/src/transaction/optimism.rs
- crates/primitives/src/transaction/tx_type.rs
- crates/rpc/rpc-types/src/eth/engine.rs
- crates/transaction-pool/src/test_utils/mock.rs
Moves feature flags below comments per Bjerg's nit
> Move feature flags below comments

- crates/primitives/src/chain/spec.rs
Rebases #15 on `clabby/op-reth`
> Use TTD(0) fork condition for OP_GOERLI Paris hardfork

- crates/primitives/src/transaction/mod.rs
- crates/revm/src/executor.rs
- crates/rpc/rpc-types/src/eth/fee.rs
- crates/storage/codecs/derive/src/arbitrary.rs
> rebase: brianbland/op reth fix primitives tx proptests

- crates/primitives/src/chain/spec.rs
- crates/primitives/src/transaction/mod.rs
- crates/primitives/src/transaction/optimism.rs
- crates/revm/src/executor.rs
Fixes the failing tests introduced in #61 & #63
> chore: fix failing tests

- Cargo.lock
- Cargo.toml
- bin/reth/src/cli/mod.rs
- bin/reth/src/debug_cmd/execution.rs
- bin/reth/src/debug_cmd/merkle.rs
- bin/reth/src/debug_cmd/mod.rs
- crates/blockchain-tree/src/blockchain_tree.rs
- crates/interfaces/src/db.rs
- crates/net/common/src/ratelimit.rs
- crates/net/dns/src/query.rs
- crates/payload/basic/src/lib.rs
- crates/revm/revm-inspectors/src/tracing/builder/parity.rs
- crates/rpc/rpc-types/src/eth/trace/parity.rs
- crates/rpc/rpc/src/debug.rs
- crates/rpc/rpc/src/eth/api/mod.rs
- crates/rpc/rpc/src/layers/jwt_validator.rs
- crates/storage/db/src/implementation/mdbx/cursor.rs
- crates/storage/db/src/implementation/mdbx/mod.rs
- crates/storage/db/src/implementation/mdbx/tx.rs
- crates/storage/db/src/lib.rs
- crates/tracing/src/lib.rs
- crates/transaction-pool/src/traits.rs
Merges `upstream/main` into `anton-rs/clabby/op-reth` for the payload builder modifications made upstream.
> chore: Sync with upstream

- Cargo.lock
- crates/revm/src/executor.rs
- crates/revm/src/optimism.rs
- crates/transaction-pool/Cargo.toml
- crates/transaction-pool/src/lib.rs
- crates/transaction-pool/src/maintain.rs
- crates/transaction-pool/src/test_utils/mock.rs
- crates/transaction-pool/src/traits.rs
- crates/transaction-pool/src/validate/eth.rs
Applies the L1 cost function for transactions in the tx pool.
> feat(transaction-pool): Apply the L1 Cost Function

- bin/reth/src/node/mod.rs
- crates/net/network/src/config.rs
- crates/net/network/src/manager.rs
- crates/net/network/src/network.rs
- crates/net/network/src/transactions.rs
Addresses https://github.com/paradigmxyz/reth/issues/3795
> feat: disable gossip when optimism CLI flag is set

- bin/reth/src/node/mod.rs
- crates/interfaces/src/executor.rs
- crates/primitives/src/receipt.rs
Performs some small nit fixes.
> fix(nits): Fixes some nits

- crates/payload/basic/src/optimism.rs
- crates/revm/src/optimism/executor.rs
Bump the nonce on a deposit EVM halt post-regolith
> Bump the nonce on deposit EVM halt

- bin/reth/src/debug_cmd/build_block.rs
- crates/payload/basic/src/lib.rs
- crates/payload/basic/src/optimism.rs
- crates/payload/builder/src/payload.rs
- crates/rpc/rpc-engine-api/src/engine_api.rs
- crates/rpc/rpc-types/src/eth/engine/payload.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376069831
> fix(rpc): Outline Optimism Payload Attributes

- crates/net/network-api/src/lib.rs
- crates/net/network-api/src/noop.rs
- crates/net/network/src/config.rs
- crates/net/network/src/manager.rs
- crates/net/network/src/network.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376084696
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376085527
> fix(net): Network Crate Fixes

- crates/rpc/rpc-types-compat/src/transaction/mod.rs
- crates/rpc/rpc-types/src/eth/engine/payload.rs
- crates/rpc/rpc-types/src/eth/transaction/mod.rs
- crates/rpc/rpc-types/src/serde_helpers/u64_hex.rs
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376119189
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376120191
> fix(rpc-types): optimism tx fields, renamed u64_hex_opt

- crates/primitives/src/constants/mod.rs
- crates/primitives/src/revm/env.rs
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376103897
- addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376108252
> chore(primitives): fill tx env in separate fn

- bin/reth/src/node/mod.rs
Adds a small comment to describe the sequencer endpoint and tx gossip disabling for optimism.
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376075723
> chore(bin): Sequencer Endpoint Comment

- crates/consensus/beacon/src/engine/mod.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376078611
> fix(consensus): Beacon Reorg Debug Stmt Control Flow

- crates/rpc/rpc/src/eth/error.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376125915
> Fix: Optimism RPC Error Variant Refactoring

- crates/interfaces/src/blockchain_tree/error.rs
- crates/interfaces/src/executor.rs
- crates/revm/src/optimism/mod.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376083955
> fix(interfaces): Optimism Error Type Hoisting

- crates/consensus/common/src/validation.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1376082479
> fix(consensus/common): Outline Gas Limit Check Function

- crates/net/network/src/config.rs
- crates/payload/builder/src/error.rs
- crates/rpc/rpc-types/src/eth/transaction/mod.rs
- crates/rpc/rpc/src/eth/api/transactions.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377437223
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377437631
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377439289
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377441359
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377442705
> Final Small Fixes

- crates/rpc/rpc/Cargo.toml
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377441729
> Final_final_2 Fixes 

- crates/rpc/rpc/src/eth/api/block.rs
- crates/rpc/rpc/src/eth/api/transactions.rs
Addresses https://github.com/paradigmxyz/reth/pull/4377#discussion_r1377443808
> fix: Outline Optimism Meta Block Fields
